AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Pipeline and Build Projects for EKS Platform deployment for a single environmentin AWS
Parameters:
    Environment:
        Type: String
        Default: tools
        Description: Short Name for the Environment being deployed in this pipeline, to be used in resource and stack names
    AppCode:
        Type: String
        Default: demo-pipeline
        Description: Short Name for the Application being deployed in this pipeline, to be used in resource and stack names
    PipelineBucket:
        Type: String
        Default: 238160719262-pipelines
        Description: Name of S3 bucket for CodePipeline to use
    PipelineBucketKMSKeyARN:
        Type: String
        Default: arn:aws:kms:ap-southeast-2:238160719262:key/db041cc6-935a-4b34-a539-d5c3ea6669ec
        Description: ARN of KMS key used for S3 pipeline bucket encryption
    CloudformationBucket:
        Type: String
        Default: 238160719262-cloudformation
        Description: Name of S3 bucket for Cloudformation Templates
    BuildBucket:
        Type: String
        Default: 238160719262-builds
        Description: Name of S3 bucket for build artefacts 
    CodeCommitRepo:
        Type: String
        Default: pipeline-test
        Description: Name of the CodeCommit Repo containing source to build / deploy with the pipeline
    CodeCommitBranch:
        Type: String
        Default: master
        Description: Name of the CodeCommit Branch for trigger pipeline
    DeploymentRoleARN:
        Type: String
        Default: arn:aws:iam::238160719262:role/Admins
        Description: ARN of the deployment role to assume in the target account when deploying cloudformation templates and CLI calls
    CodeBuildImage:
        Type: String
        Default: "aws/codebuild/standard:5.0"
        Description: Name of the image to use for the CodeBuild container
    CodeBuildCompute:
      Type: String
      Default: "BUILD_GENERAL1_MEDIUM"
      Description: Container Size to use for the CodeBuild container
Resources:
    PreDeployProject:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: !Sub ${AppCode}-${Environment}-predeploy-project
            EncryptionKey: !Ref PipelineBucketKMSKeyARN
            Artifacts:
                Type: CODEPIPELINE
            Environment: 
                Type: LINUX_CONTAINER
                ComputeType: !Ref CodeBuildCompute
                Image: !Ref CodeBuildImage
                PrivilegedMode: true
                EnvironmentVariables:
                  - Name: BUILD_OUTPUT_BUCKET
                    Value: !Ref BuildBucket
                  - Name: CLOUDFORMATION_BUCKET
                    Value: !Ref CloudformationBucket
            ServiceRole: !GetAtt PipelineRole.Arn
            Source: 
                Type: CODEPIPELINE
                BuildSpec: buildspec-predeploy.yaml
    DeployProject:
        Type: AWS::CodeBuild::Project
        Properties:
            Name: !Sub ${AppCode}-${Environment}-deploy-project
            EncryptionKey: !Ref PipelineBucketKMSKeyARN
            Artifacts:
                Type: CODEPIPELINE
            Environment: 
                Type: LINUX_CONTAINER
                ComputeType: !Ref CodeBuildCompute
                Image: !Ref CodeBuildImage
                PrivilegedMode: true
                EnvironmentVariables:
                  - Name: BUILD_OUTPUT_BUCKET
                    Value: !Ref BuildBucket
                  - Name: CLOUDFORMATION_BUCKET
                    Value: !Ref CloudformationBucket
            ServiceRole: !GetAtt PipelineRole.Arn
            Source: 
                Type: CODEPIPELINE
                BuildSpec: buildspec-deploy.yaml
    PipelinePolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action: 
                - 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${PipelineBucket}/*'
                - !Sub 'arn:aws:s3:::${PipelineBucket}'
                - !Sub 'arn:aws:s3:::${CloudformationBucket}/*'
                - !Sub 'arn:aws:s3:::${CloudformationBucket}'
                - !Sub 'arn:aws:s3:::${BuildBucket}/*'
                - !Sub 'arn:aws:s3:::${BuildBucket}'
            - Effect: Allow
              Action:
                - 'iam:PassRole'
              Resource: 
                - '*'
            - Effect: Allow
              Action:
                - 'codepipeline:PutJobSuccessResult'
                - 'codepipeline:PutJobFailureResult'
              Resource:
                - !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${AppCode}-${Environment}-pipeline
            - Effect: Allow
              Action:
                - 'codecommit:*'
              Resource: 
                - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepo}'
            - Effect: Allow
              Action:
                - 'codebuild:StartBuild'
                - 'codebuild:BatchGetBuilds'
              Resource: 
                - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AppCode}-${Environment}-predeploy-project'
                - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AppCode}-${Environment}-deploy-project'
            - Effect: Allow
              Action:
                - 'kms:*'
              Resource: 
                - !Ref PipelineBucketKMSKeyARN
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: 
                - !Ref DeploymentRoleARN
    PipelineRole:
      Type: AWS::IAM::Role
      Properties:
          RoleName: !Sub '${AppCode}-${Environment}-CodePipeline-Role'
          AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Action: 
                  - 'sts:AssumeRole'
                  Effect: Allow
                  Principal:
                    Service: 
                      - codepipeline.amazonaws.com
                - Action: 
                  - 'sts:AssumeRole'
                  Effect: Allow
                  Principal:
                    Service: 
                      - codebuild.amazonaws.com
                - Action: 
                  - 'sts:AssumeRole'
                  Effect: Allow
                  Principal:
                    Service: 
                      - lambda.amazonaws.com
          Path: /
          ManagedPolicyArns:
              - !Ref PipelinePolicy
    Pipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            ArtifactStore: 
                Location: !Ref PipelineBucket
                Type: S3
                EncryptionKey:
                  Id: !Ref PipelineBucketKMSKeyARN
                  Type: KMS
            Name: !Sub ${AppCode}-${Environment}-pipeline
            RoleArn: !GetAtt PipelineRole.Arn
            Stages:
                - Name: Source
                  Actions:
                    - Name: Source
                      ActionTypeId:
                        Category: Source
                        Owner: AWS
                        Provider: CodeCommit
                        Version: 1
                      Configuration:
                        RepositoryName: !Ref CodeCommitRepo
                        BranchName: !Ref CodeCommitBranch
                      OutputArtifacts:
                        - Name: SourceZip
                      RunOrder: 1
                - Name: PreDeploy
                  Actions:
                    - Name: PreDeploy
                      Namespace: predeploy
                      ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Provider: CodeBuild
                        Version: 1
                      Configuration:
                        ProjectName: !Ref PreDeployProject
                        EnvironmentVariables: !Sub '[
                          {"name":"DEPLOYMENT_ROLE","value":"${DeploymentRoleARN}","type":"PLAINTEXT"},
                          {"name":"APP_CODE","value":"${AppCode}","type":"PLAINTEXT"},
                          {"name":"ENVIRONMENT","value":"${Environment}","type":"PLAINTEXT"}
                          ]'
                      InputArtifacts:
                        - Name: SourceZip
                      OutputArtifacts:
                        - Name: PreDeployZip
                      RunOrder: 1
                - Name: Approve-Deployment
                  Actions:
                    - Name: Approve-Deployment
                      ActionTypeId:
                        Category: Approval
                        Owner: AWS
                        Provider: Manual
                        Version: 1
                      RunOrder: 1                    
                - Name: Deploy
                  Actions:
                    - Name: Deploy-Code
                      Namespace: deploy
                      ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Provider: CodeBuild
                        Version: 1
                      Configuration:
                        ProjectName: !Ref DeployProject
                        EnvironmentVariables: !Sub '[
                          {"name":"DEPLOYMENT_ROLE","value":"${DeploymentRoleARN}","type":"PLAINTEXT"},
                          {"name":"APP_CODE","value":"${AppCode}","type":"PLAINTEXT"},
                          {"name":"ENVIRONMENT","value":"${Environment}","type":"PLAINTEXT"}
                          ]'
                      InputArtifacts:
                        - Name: SourceZip
                      OutputArtifacts:
                        - Name: PostDeployZip
                      RunOrder: 1
