apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::${DEPLOYMENT_ACCOUNT}:role/${EKS_NODE_INSTANCE_ROLE_NAME}
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: ${KUBE_ADMIN_ROLE}
      username: platformadmins
    - groups:
      - system:masters
      rolearn: ${KUBE_POWERUSER_ROLE}
      username: powerusers
    - groups:
      - system:masters
      rolearn: ${KUBE_READONLY_ROLE}
      username: readonly
