AWSTemplateFormatVersion: '2010-09-09'
Description: Creates build and deployment roles for app pipelines
Parameters:
  AppCode:
      Type: String
      Default: base
      Description: Short Name for the Application being deployed, to be used in resource and stack names
  DevOpsAccountID:
    Description: AWS AccountNumber for DevOps account deployments
    Type: String
    Default: 238160719262
  DeploymentAccountIds:
    Description: AWS AccountNumber for prod
    Type: CommaDelimitedList
    Default: "967792619409,271005954527"
  BuildRoleSuffix:
      Type: String
      Default: Build-Role
      Description: Suffix for IAM Build role being created
  DeploymentRoleSuffix:
      Type: String
      Default: Deployment-Role
      Description: Suffix for IAM Deployment role being created
  AppCode:
      Type: String
      Default: base
      Description: Short Name for the Application being deployed, to be used in resource and stack names
  PrimaryRegion:
    Description: Primary Region ID to detect where to deploy account wide resources
    Type: String
    Default: ap-southeast-2
Conditions:
  IsDevOpsAccount: !Equals 
    - !Ref DevOpsAccountID
    - !Ref AWS::AccountId
  IsPrimaryRegion: !Equals 
    - !Ref PrimaryRegion
    - !Ref AWS::Region
  IsPrimaryAndDevOpsAccount: !And 
    - !Condition IsPrimaryRegion
    - !Condition IsDevOpsAccount

Resources:
  DeploymentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsPrimaryRegion
    Properties: 
      Description: Deployment Role Access"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - '*'
            Resource: '*'
      ManagedPolicyName: !Sub '${AppCode}-Deployment-Policy'
  DeploymentRole:
    Type: 'AWS::IAM::Role'
    Condition: IsPrimaryRegion
    Properties:
      RoleName: !Sub '${AppCode}-${DeploymentRoleSuffix}'
      ManagedPolicyArns: 
        - !Ref DeploymentPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DevOpsAccountID}:role/${AppCode}-CodePipeline-Role
            Action: 'sts:AssumeRole'

  BuildPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsPrimaryRegion
    Properties: 
      Description: Build Role Access"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - '*'
            Resource: '*'
      ManagedPolicyName: !Sub '${AppCode}-Build-Policy'
  BuildRole:
    Type: 'AWS::IAM::Role'
    Condition: IsPrimaryRegion
    Properties:
      RoleName: !Sub '${AppCode}-${BuildRoleSuffix}'
      ManagedPolicyArns: 
        - !Ref DeploymentPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${DevOpsAccountID}:role/${AppCode}-CodePipeline-Role
            Action: 'sts:AssumeRole'

Outputs:
  DeploymentRole:
    Condition: IsPrimaryRegion
    Value: !Ref DeploymentRole
    Export:
      Name: !Sub '${AppCode}-Deployment-Role'
  BuildRole:
    Condition: IsPrimaryAndDevOpsAccount
    Value: !Ref BuildRole
    Export:
      Name: !Sub ${AppCode}-Build-Role
