version: 0.2

env:
  variables:
    VERSION: "1234567"
    CODE_FILE: index.html
    IMAGE_REPO_ROOT: 238160719262.dkr.ecr.ap-southeast-2.amazonaws.com
    IMAGE_NAME: ecs-demo-app

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - echo Getting latest commit hash
      - VERSION=`echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7`
      - echo $VERSION
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Building the Docker image...
      - echo docker build -t $IMAGE_NAME:$VERSION -f DockerFile --build-arg NODE_FILE=$CODE_FILE .
      - docker build -t $IMAGE_NAME:$VERSION -f DockerFile --build-arg NODE_FILE=$CODE_FILE .
      - echo docker tag $IMAGE_NAME:$VERSION $IMAGE_REPO_ROOT/$IMAGE_NAME:$VERSION
      - docker tag $IMAGE_NAME:$VERSION $IMAGE_REPO_ROOT/$IMAGE_NAME:$VERSION
      - echo docker tag $IMAGE_NAME:$VERSION $IMAGE_REPO_ROOT/$IMAGE_NAME:latest
      - docker tag $IMAGE_NAME:$VERSION $IMAGE_REPO_ROOT/$IMAGE_NAME:latest
  post_build:
    commands:
      - echo Make sure the ECR Repo is there...
      - echo aws ecr create-repository --repository-name=$IMAGE_NAME
      - aws ecr create-repository --repository-name=$IMAGE_NAME 2>/dev/null; true
      - echo Pushing the Docker image...
      - echo docker push $IMAGE_REPO_ROOT/$IMAGE_NAME:$VERSION
      - docker push $IMAGE_REPO_ROOT/$IMAGE_NAME:$VERSION
      - echo docker push $IMAGE_REPO_ROOT/$IMAGE_NAME:latest
      - docker push $IMAGE_REPO_ROOT/$IMAGE_NAME:latest
      - echo Build completed on `date`
