# escape=\
FROM node

ARG NODE_FILE
ENV NODE_FILE=$NODE_FILE

#copy jar
WORKDIR /opt
RUN mkdir origin
RUN echo COPY ./ /opt/origin/
COPY ./ "/opt/origin/"
RUN chmod 664 /opt/origin/*
WORKDIR /opt/origin
RUN npm install

EXPOSE 80
CMD node server.js
