AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates a Build and single Account Deploy Code Pipeline with additional lambda and SNS/ Lambda event integration, calling shell scripts to run build and deploy actions
Parameters:
    AppCode:
        Type: String
        Default: base
        Description: Short Name for the Application being deployed in this pipeline, to be used in resource and stack names
    PipelineBucket:
        Type: String
        Default: 238160719262-pipelines
        Description: Name of S3 bucket for CodePipeline to use
    PipelineBucketKMSKeyAliasARN:
        Type: String
        Default: arn:aws:kms:ap-southeast-2:238160719262:key/db041cc6-935a-4b34-a539-d5c3ea6669ec
        Description: ARN of KMS key used for S3 pipeline bucket encryption
    CloudformationBucket:
        Type: String
        Default: 238160719262-cloudformation
        Description: Name of S3 bucket for Cloudformation Templates
    BuildBucket:
        Type: String
        Default: 238160719262-builds
        Description: Name of S3 bucket for build artefacts 
    CodeCommitRepoName:
        Type: String
        Default: pipeline-test
        Description: Name of the CodeCommit Repo containing source to build / deploy with the pipeline
    CodeCommitBranchName:
        Type: String
        Default: master
        Description: Name of the CodeCommit Branch for trigger pipeline
    DeploymentRoleARNAdmin:
        Type: String
        Default: arn:aws:iam::238160719262:role/DeploymentAdmin
        Description: ARN of the deployment role to assume in the target account when deploying cloudformation templates and CLI calls
    BuildRoleARN:
        Type: String
        Default: arn:aws:iam::238160719262:role/DeploymentAdmin
        Description: ARN of the deployment role to assume in the target account when deploying cloudformation templates and CLI calls
    CodeBuildImage:
        Type: String
        Default: "aws/codebuild/standard:6.0"
        Description: Name of the image to use for the CodeBuild container
    CodeBuildCompute:
      Type: String
      Default: "BUILD_GENERAL1_SMALL"
      Description: Container Size to use for the CodeBuild container
    CodeBuildType:
      Type: String
      Default: "LINUX_CONTAINER"
      Description: Compute Architecture to use for the CodeBuild container
    VPCID:
      Type: String
      Default: ""
      Description: The VPC for CodeBuild projects to run in
    VPCSubnetIDs:
      Type: CommaDelimitedList
      Default: ""
      Description: The Subnets for CodeBuild projects to run in. These should be private and use NATGW egress
    VPCSecGroupID:
      Type: String
      Default: ""
      Description: The SecurityGroup for CodeBuild projects to use. It needs Egress Only
    LambdaBucket:
        Type: String
        Default: 238160719262-deployments
        Description: Name of S3 bucket for Lambda code bundles
    PipelineActionFunctionBucketKey:
        Type: String
        Default: 238160719262-pipelines
        Description: Name of S3 key for Stage Function Code Bundle
    PipelineSNSFunctionBucketKey:
        Type: String
        Default: 238160719262-pipelines
        Description: Name of S3 key for SNS Function Code Bundle
Conditions:
  UseVPC: !Not
    - !Equals
      - !Ref  VPCID
      - ""
Resources:
    BuildProjectLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        LogGroupName: !Sub '/aws/codebuild/${AppCode}-build-project'
        RetentionInDays: 14
    BuildProject:
        Type: AWS::CodeBuild::Project
        DependsOn: BuildProjectLogGroup
        Properties:
            Name: !Sub ${AppCode}-build-project
            EncryptionKey: !Ref PipelineBucketKMSKeyAliasARN
            Artifacts:
                Type: CODEPIPELINE
            Environment: 
                Type: !Ref CodeBuildType
                ComputeType: !Ref CodeBuildCompute
                Image: !Ref CodeBuildImage
                PrivilegedMode: true
                EnvironmentVariables:
                  - Name: BUILD_OUTPUT_BUCKET
                    Value: !Ref BuildBucket
                  - Name: CLOUDFORMATION_BUCKET
                    Value: !Ref CloudformationBucket
            ServiceRole: !GetAtt PipelineRole.Arn
            Source: 
                Type: CODEPIPELINE
                BuildSpec: cicd/buildspec.yaml
            VpcConfig:
              !If
              - UseVPC
              - 
                VpcId: !Ref VPCID
                Subnets: !Ref VPCSubnetIDs
                SecurityGroupIds: 
                  - !Ref VPCSecGroupID
              - !Ref "AWS::NoValue"
    DeployProjectLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        LogGroupName: !Sub '/aws/codebuild/${AppCode}-deploy-project'
        RetentionInDays: 14
    DeployProject:
        Type: AWS::CodeBuild::Project
        DependsOn: DeployProjectLogGroup
        Properties:
            Name: !Sub ${AppCode}-deploy-project
            EncryptionKey: !Ref PipelineBucketKMSKeyAliasARN
            Artifacts:
                Type: CODEPIPELINE
            Environment: 
                Type: !Ref CodeBuildType
                ComputeType: !Ref CodeBuildCompute
                Image: !Ref CodeBuildImage
                PrivilegedMode: true
                EnvironmentVariables:
                  - Name: BUILD_OUTPUT_BUCKET
                    Value: !Ref BuildBucket
                  - Name: CLOUDFORMATION_BUCKET
                    Value: !Ref CloudformationBucket
            ServiceRole: !GetAtt PipelineRole.Arn
            Source: 
                Type: CODEPIPELINE
                BuildSpec: cicd/buildspec-deploy.yaml
            VpcConfig:
              !If
              - UseVPC
              - 
                VpcId: !Ref VPCID
                Subnets: !Ref VPCSubnetIDs
                SecurityGroupIds: 
                  - !Ref VPCSecGroupID
              - !Ref "AWS::NoValue"
    PipelinePolicy:
      Type: AWS::IAM::ManagedPolicy
      Properties:
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: 
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action: 
                - 's3:*'
              Resource:
                - !Sub 'arn:aws:s3:::${PipelineBucket}/*'
                - !Sub 'arn:aws:s3:::${PipelineBucket}'
                - !Sub 'arn:aws:s3:::${CloudformationBucket}/*'
                - !Sub 'arn:aws:s3:::${CloudformationBucket}'
                - !Sub 'arn:aws:s3:::${BuildBucket}/*'
                - !Sub 'arn:aws:s3:::${BuildBucket}'
            - Effect: Allow
              Action:
                - 'iam:PassRole'
              Resource: 
                - '*'
            - Effect: Allow
              Action:
                - 'codepipeline:PutJobSuccessResult'
                - 'codepipeline:PutJobFailureResult'
              Resource:
                - "*"
            - Effect: Allow
              Action:
                - 'codecommit:*'
              Resource: 
                - !Sub 'arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${CodeCommitRepoName}'
            - Effect: Allow
              Action:
                - 'codebuild:StartBuild'
                - 'codebuild:BatchGetBuilds'
              Resource: 
                - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AppCode}-build-project'
                - !Sub 'arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${AppCode}-deploy-project'
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource: 
                - !Ref BuildRoleARN
                - !Ref DeploymentRoleARNAdmin
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: 
                - '*'
            - Effect: Allow
              Action:
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
              Resource: 
                - "*"
    PipelineRole:
      Type: AWS::IAM::Role
      DependsOn: PipelinePolicy
      Properties:
          RoleName: !Sub '${AppCode}-CodePipeline-Role'
          AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Action: 
                  - 'sts:AssumeRole'
                  Effect: Allow
                  Principal:
                    Service: 
                      - codepipeline.amazonaws.com
                - Action: 
                  - 'sts:AssumeRole'
                  Effect: Allow
                  Principal:
                    Service: 
                      - codebuild.amazonaws.com
                - Action: 
                  - 'sts:AssumeRole'
                  Effect: Allow
                  Principal:
                    Service: 
                      - lambda.amazonaws.com
          Path: /
          ManagedPolicyArns:
              - !Ref PipelinePolicy
    Pipeline:
        Type: AWS::CodePipeline::Pipeline
        Properties:
            ArtifactStore: 
                Location: !Ref PipelineBucket
                Type: S3
                EncryptionKey:
                  Id: !Ref PipelineBucketKMSKeyAliasARN
                  Type: KMS
            Name: !Sub ${AppCode}-pipeline-lambda-sns
            RoleArn: !GetAtt PipelineRole.Arn
            Stages:
                - Name: Source
                  Actions:
                    - Name: Source
                      Namespace: Source
                      ActionTypeId:
                        Category: Source
                        Owner: AWS
                        Provider: CodeCommit
                        Version: 1
                      Configuration:
                        RepositoryName: !Ref CodeCommitRepoName
                        BranchName: !Ref CodeCommitBranchName
                      OutputArtifacts:
                        - Name: SourceZip
                      RunOrder: 1
                - Name: Lambda
                  Actions:
                    - Name: Lambda
                      ActionTypeId:
                        Category: Invoke
                        Owner: AWS
                        Provider: Lambda
                        Version: '1'
                      RunOrder: 1
                      Configuration:
                        FunctionName: !Sub '${AppCode}-PipelineActionFunction'
                        UserParameters: !Sub '{
                          "PIPELINE_NAME": "${AppCode}-pipeline-lambda-sns", 
                          "REPOSITORY_NAME": " ${CodeCommitRepoName}",
                          "REPOSITORY_BRANCH": "${CodeCommitBranchName}", 
                          "COMMIT_ID": "#{Source.CommitId}",
                          "EXECUTION_ID": "#{codepipeline.PipelineExecutionId}"
                          }'                
                      InputArtifacts:
                        - Name: SourceZip
                - Name: Build
                  Actions:
                    - Name: Build
                      Namespace: build
                      ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Provider: CodeBuild
                        Version: 1
                      Configuration:
                        ProjectName: !Ref BuildProject
                        EnvironmentVariables: !Sub '[
                          {"name":"BUILD_ROLE","value":"${BuildRoleARN}","type":"PLAINTEXT"},
                          {"name":"APP_CODE","value":"${AppCode}","type":"PLAINTEXT"},
                          {"name":"ENVIRONMENT","value":"shared","type":"PLAINTEXT"},
                          {"name":"REGION","value":"${AWS::Region}","type":"PLAINTEXT"}
                          ]'
                      InputArtifacts:
                        - Name: SourceZip
                      OutputArtifacts:
                        - Name: BuildZip
                      RunOrder: 1
                - Name: Approve-Deployment
                  Actions:
                    - Name: Approve-Deployment
                      ActionTypeId:
                        Category: Approval
                        Owner: AWS
                        Provider: Manual
                        Version: 1
                      RunOrder: 1                    
                - Name: Deploy
                  Actions:
                    - Name: DeployAdmin
                      Namespace: deployadmin
                      ActionTypeId:
                        Category: Build
                        Owner: AWS
                        Provider: CodeBuild
                        Version: 1
                      Configuration:
                        ProjectName: !Ref DeployProject
                        EnvironmentVariables: !Sub '[
                          {"name":"DEPLOYMENT_ROLE","value":"${DeploymentRoleARNAdmin}","type":"PLAINTEXT"},
                          {"name":"APP_CODE","value":"${AppCode}","type":"PLAINTEXT"},
                          {"name":"ENVIRONMENT","value":"admin","type":"PLAINTEXT"},
                          {"name":"REGION","value":"${AWS::Region}","type":"PLAINTEXT"},
                          {"name":"COMMIT_ID","value":"#{Source.CommitId}","type":"PLAINTEXT"}
                          ]'
                      InputArtifacts:
                        - Name: BuildZip
                      RunOrder: 1

    PipelineActionFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - "sts:AssumeRole"
        RoleName: !Sub "${AppCode}-PipelineActionFunction-Role"
        ManagedPolicyArns:
          - !Sub "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        Path: /
        Policies:
          - PolicyName: CodePipelineAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - codepipeline:PutJobSuccessResult
                    - codepipeline:PutJobFailureResult
                  Resource:
                    - '*'
    PipelineActionFunctionLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        LogGroupName: !Sub '/aws/lambda/${AppCode}-PipelineActionFunction'
        RetentionInDays: 14
    PipelineActionFunction:
      Type: AWS::Lambda::Function
      DependsOn: PipelineActionFunctionLogGroup
      Properties:
        Code:
          S3Bucket: !Ref LambdaBucket
          S3Key: !Ref PipelineActionFunctionBucketKey
        Role:
          Fn::GetAtt:
          - PipelineActionFunctionRole
          - Arn
        Handler: lambda.handler
        Runtime: python3.10
        MemorySize: 128
        Timeout: 10
        FunctionName: !Sub '${AppCode}-PipelineActionFunction'
        Environment:
          Variables:
            APP_CODE: !Ref AppCode
            REPOSITORY_NAME: !Ref CodeCommitRepoName
    PipelineSNSFunctioRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - "sts:AssumeRole"
        RoleName: !Sub "${AppCode}-PipelineSNSFunction-Role"
        ManagedPolicyArns:
          - !Sub "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        Path: /
    PipelineSNSFunctionLogGroup:
      Type: 'AWS::Logs::LogGroup'
      Properties:
        LogGroupName: !Sub '/aws/lambda/${AppCode}-PipelineSNSFunction'
        RetentionInDays: 14
    PipelineSNSFunction:
      Type: AWS::Lambda::Function
      DependsOn: PipelineSNSFunctionLogGroup
      Properties:
        Code:
          S3Bucket: !Ref LambdaBucket
          S3Key: !Ref PipelineSNSFunctionBucketKey
        Role:
          Fn::GetAtt:
          - PipelineSNSFunctioRole
          - Arn
        Handler: lambda.handler
        Runtime: python3.10
        MemorySize: 128
        Timeout: 10
        FunctionName: !Sub '${AppCode}-PipelineSNSFunction'
        Environment:
          Variables:
            APP_CODE: !Ref AppCode

    CodePipelineListener: 
      Type: AWS::Events::Rule
      Properties: 
        Description: "Code Pipeline Listener"
        EventPattern:
          source:
            - aws.codepipeline
          detail-type:
            - 'CodePipeline Pipeline Execution State Change'
            - 'CodePipeline Stage Execution State Change'
          detail:
            state:
            - FAILED
            - STARTED
            - CANCELED
            - SUCCEEDED
          resources:
            - !Sub 'arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${AppCode}-pipeline-lambda-sns'
        Targets: 
          - 
            Arn: !Ref PipelineSNSTopic
            Id: "PipelineSNSTopic"
    CodePipelineListenerInvokePermission:
      Type: AWS::Lambda::Permission
      Properties: 
        FunctionName:  !GetAtt
        - PipelineSNSFunction
        - Arn
        Action: lambda:InvokeFunction
        Principal: events.amazonaws.com
        SourceArn: !GetAtt CodePipelineListener.Arn 

    PipelineSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: !Sub '${AppCode}-pipeline-sns-topic'
        TopicName: !Sub '${AppCode}-pipeline-sns-topic'
        Subscription:
          - Protocol: lambda
            Endpoint: !GetAtt PipelineSNSFunction.Arn
    PipelineSNSTopicPolicy:
      Type: 'AWS::SNS::TopicPolicy'
      Properties:
        Topics:
          - !Ref PipelineSNSTopic
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'sns:Publish'
              Resource: !Ref PipelineSNSTopic
              Principal:
                AWS: '*'
              Condition:
                ArnLike:
                  AWS:SourceArn: !Sub 'arn:aws:*:*:${AWS::AccountId}:*'
    PipelineSNSTopicInvokePermission:
      Type: 'AWS::Lambda::Permission'
      Properties:
        Action: 'lambda:InvokeFunction'
        FunctionName: !Ref PipelineSNSFunction
        Principal: sns.amazonaws.com   
