AWSTemplateFormatVersion: '2010-09-09'
Description: Creates pre-requisite S3 buckets, policies, KMS key and cross account access for centralised deployment pipelines
Parameters:
  AppCode:
      Type: String
      Default: base
      Description: Short Name for the Application being deployed, to be used in resource and stack names
  PipelineBucketKMSKeyAlias:
      Type: String
      Default: alias/devops-bucket-key
      Description: KMS key alias used for codepipeline S3 bucket encryption
  DevOpsAccountID:
    Description: AWS AccountNumber for DevOps account
    Type: String
    Default: 238160719262
  DeploymentAccountIds:
    Description: AWS AccountNumbers for KMS access
    Type: CommaDelimitedList
    Default: "238160719262,967792619409,271005954527,470368177909,101526008094"
  PipelineRoles:
    Description: IAM Pipeline Deployment Roles for KMS access
    Type: CommaDelimitedList
    Default: "arn:aws:iam::238160719262:role/*-CodePipeline-Role"
  LoggingBucketName:
    Description: Name of S3 Bucket used for Access Logs.
    Type: String
    Default: "238160719262-logging"
  PipelineBucketName:
    Description: Name of S3 Bucket used for Code Pipeline artifacts.
    Type: String
    Default: "238160719262-codepipeline"
  BuildBucketName:
    Description: Name of S3 Bucket used for Build Output.
    Type: String
    Default: "238160719262-builds"
  EnableDevOps:
    Description: Bool value whether to create the resources (these incur KMS costs). Only required if using CodePipelines.
    Type: String 
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  PrimaryRegion:
    Description: Primary Region ID to detect where to deploy account wide resources
    Type: String
    Default: ap-southeast-2
Conditions:
  IsPrimaryRegion: !Equals 
    - !Ref PrimaryRegion
    - !Ref AWS::Region
  DeployDevOps: !Equals 
    - !Ref EnableDevOps
    - "true"

Resources:
  PipelineKMSKey:
    Type: AWS::KMS::Key
    Condition: DeployDevOps
    Properties:
      Description: Used by Pipeline Role and Resource Deployment Roles for Pipeline Artifacts
      EnableKeyRotation: false
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref AWS::StackName
        Statement:
          -
            Sid: Allows delegated admin of the key
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:*"
            Resource: "*"
          -
            Sid: Allows delegated use of the key
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
          -
            Sid: Allows codepipeline use of the key
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
            Condition:
              ArnLike:
                aws:PrincipalArn: !Ref PipelineRoles
          -
            Sid: Allow delegated cross account use of the key
            Effect: Allow
            Principal:
              AWS: !Ref DeploymentAccountIds
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
  PipelineKMSKeyAlias:
    Type: AWS::KMS::Alias
    Condition: DeployDevOps
    Properties:
      AliasName: !Ref PipelineBucketKMSKeyAlias
      TargetKeyId: !Ref PipelineKMSKey
  PipelineBucket:
    Type: AWS::S3::Bucket
    Condition: DeployDevOps
    Properties:
      BucketName: !Ref PipelineBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Sub '${PipelineKMSKey}'
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucketName
        LogFilePrefix: !Sub S3AccessLogs/${PipelineBucketName}/
      LifecycleConfiguration:
        Rules:
          - Id: PipelineBucketRule
            Status: Enabled
            ExpirationInDays: 7
  PipelineBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Condition: DeployDevOps
    Properties: 
      Bucket: !Ref PipelineBucket
      PolicyDocument: 
        Statement: 
          - 
            Sid: Allows Accounts access to pipeline bucket
            Action: 
              - "s3:*"
            Effect: "Allow"
            Resource: 
              - !Sub '${PipelineBucket.Arn}/*'
              - !Sub '${PipelineBucket.Arn}'
            Principal: 
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          - 
            Sid: Allows Accounts access to pipeline bucket
            Action: 
              - "s3:*"
            Effect: "Allow"
            Resource: 
              - !Sub '${PipelineBucket.Arn}/*'
              - !Sub '${PipelineBucket.Arn}'
            Principal: 
              AWS: !Ref DeploymentAccountIds
  BuildBucket:
    Type: AWS::S3::Bucket
    Condition: DeployDevOps
    Properties:
      BucketName: !Ref BuildBucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !Sub '${PipelineKMSKey}'
      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucketName
        LogFilePrefix: !Sub S3AccessLogs/${BuildBucketName}/
  BuildBucketPolicy: 
    Type: AWS::S3::BucketPolicy
    Condition: DeployDevOps
    Properties: 
      Bucket: !Ref BuildBucket
      PolicyDocument: 
        Statement: 
          - 
            Sid: Allows Cross Account access to build bucket
            Action: 
              - "s3:*"
            Effect: "Allow"
            Resource: 
              - !Sub '${BuildBucket.Arn}/*'
              - !Sub '${BuildBucket.Arn}'
            Principal: 
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
          - 
            Sid: Allows Cross Account access to build bucket
            Action: 
              - "s3:*"
            Effect: "Allow"
            Resource: 
              - !Sub '${BuildBucket.Arn}/*'
              - !Sub '${BuildBucket.Arn}'
            Principal: 
              AWS: !Ref DeploymentAccountIds
Outputs:
  PipelineBucket:
    Condition: DeployDevOps
    Value: !Ref PipelineBucket
    Export:
      Name: !Sub 'PipelineBucketName'
  BuildBucket:
    Condition: DeployDevOps
    Value: !Ref BuildBucket
    Export:
      Name: !Sub 'BuildBucketName'
