AWSTemplateFormatVersion: '2010-09-09'
Description: 'Provisions a VPC Prefix list for use in secgroups'
Parameters:
  Environment:
    Type: String
    Description: Enter Environment name
    Default: demo

Resources:
  VPNPrefixList:
    Type: AWS::EC2::PrefixList
    Properties:
      PrefixListName: !Sub '${Environment}-PrefixList'
      AddressFamily: "IPv4"
      MaxEntries: 20
      Entries:
        - Cidr: "1.2.3.4/32"
          Description: "Allowed IP"
      Tags:
        - Key: "Name"
          Value: "OC-Whitelist-PrefixList"

Outputs:
  VPNPrefixList:
    Description: A reference to the Prefix List for whitelisting access
    Value: !Ref VPNPrefixList
    Export:
      Name: !Sub '${Environment}-PrefixList'