  AWSTemplateFormatVersion: "2010-09-09"
  Description: "Creates a VPC with optional NAT Gateway, VPC Peering and/or VPN Endpoint"
  Parameters:
    CreatePeeringConnection:
      Description: Create or remove VPC Peering Connection.
      Type: String
      Default: true
      AllowedValues: [true, false]
    CreatePeeringRoute:
      Description: Create or remove Route table entries for the VPC Peering Connection.
      Type: String
      Default: true
      AllowedValues: [true, false]
    LocalVPCID:
      Description: The VPC ID of the VPC being peered from.
      Type: String
      Default: "vpc-1234567890"
    LocalPublicRouteTableID:
      Description: The route table ID for the local VPC public subnet.
      Type: String
      Default: "rtb-11112222"
    LocalPrivateRouteTableAZ1ID:
      Description: The route table ID for the local VPC public subnet.
      Type: String
      Default: "rtb-11112222"
    LocalPrivateRouteTableAZ2ID:
      Description: The route table ID for the local VPC public subnet.
      Type: String
      Default: "rtb-11112222"
    PeerVPCID:
      Description: The VPC ID of the VPC being peered to.
      Type: String
      Default: 'vpc-1234567890'
    PeerVPCAccountID:
      Description: The accountID containing the VPC to peer to.
      Type: String
      Default: "111111111111"
    PeerVPCRoleArn:
      Description: The arn of the peering role to assume.
      Type: String
    PeerVPCCIDRBlock:
      Description: The CIDR Block of the Peered VPC.
      Type: String
      Default: "10.10.0.0/16"
    PeerVPCConnection:
      Description: The Existing Peering Connection ID of the Peered VPC to route to.
      Type: String
      Default: "pcx-0db81971e1538fec5"
  Conditions:
    ShouldCreatePeeringConnection:
      !Equals [true, !Ref CreatePeeringConnection]
    ShouldCreatePeeringRoute:
      !Equals [true, !Ref CreatePeeringRoute]
  
  Resources:
    VPCPeeringConnection:
      Type: 'AWS::EC2::VPCPeeringConnection'
      Condition: ShouldCreatePeeringConnection
      Properties:
        VpcId: !Ref LocalVPCID
        PeerVpcId: !Ref PeerVPCID
        PeerOwnerId: !Ref PeerVPCAccountID
        PeerRegion: !Sub '${AWS::Region}'
        PeerRoleArn: !Ref PeerVPCRoleArn
    PublicRouteToPeeredVPC:
      Type: 'AWS::EC2::Route'
      Condition: ShouldCreatePeeringRoute
      Properties:
        DestinationCidrBlock: !Ref PeerVPCCIDRBlock
        RouteTableId: !Ref LocalPublicRouteTableID
        VpcPeeringConnectionId: !Ref VPCPeeringConnection
    PrivateRouteToPeeredVPC0:
      Type: 'AWS::EC2::Route'
      Condition: ShouldCreatePeeringRoute
      Properties:
        DestinationCidrBlock: !Ref PeerVPCCIDRBlock
        RouteTableId: !Ref LocalPrivateRouteTableAZ1ID
        VpcPeeringConnectionId: !Ref VPCPeeringConnection
    PrivateRouteToPeeredVPC1:
      Type: 'AWS::EC2::Route'
      Condition: ShouldCreatePeeringRoute
      Properties:
        DestinationCidrBlock: !Ref PeerVPCCIDRBlock
        RouteTableId: !Ref LocalPrivateRouteTableAZ2ID
        VpcPeeringConnectionId: !Ref VPCPeeringConnection
