AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates IAM Roles for team members to assume with varying levels of access, and IAM Groups to manage the assume role rights if deploying this atack into the Admin Account itself
Parameters:
  AdminAccount:
    Description: Account ID for AWS Account with IAM Users
    Type: String 
    Default: "238160719262"
  EnforceMFA:
    Description: Requires Accounts assuming roles to have MFA enabled
    Type: String 
    Default: "true"
    AllowedValues:
      - 'true'
      - 'false'
  IsNonProdAccount:
    Description: Bool value if current account is Production level
    Type: String 
    Default: "false"
    AllowedValues:
      - 'true'
      - 'false'

Conditions:
  ShouldEnforceMFA: !Equals 
    - !Ref EnforceMFA
    - "true"
  IsNonProd: !Equals 
    - !Ref IsNonProdAccount
    - "true"
  IsAdmin: !Equals 
    - !Ref AdminAccount
    - !Sub '${AWS::AccountId}'

Resources:
  AdminsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'PlatformAdmins'
      ManagedPolicyArns: 
        - !Ref AdminsPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']
  PowerUsersRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'PlatformPowerUsers'
      ManagedPolicyArns: 
        - !Ref PowerUsersPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']
  PowerUsersNonProdRole:
    Type: 'AWS::IAM::Role'
    Condition: IsNonProd
    Properties:
      RoleName: !Sub 'PlatformPowerUsersNonProd'
      ManagedPolicyArns: 
        - !Ref PowerUsersNonProdPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']
  ReadOnlyRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'PlatformReadOnly'
      ManagedPolicyArns: 
        - !Ref ReadOnlyPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']
  ReadOnlyNonProdRole:
    Type: 'AWS::IAM::Role'
    Condition: IsNonProd
    Properties:
      RoleName: !Sub 'PlatformReadOnlyNonProd'
      ManagedPolicyArns: 
        - !Ref ReadOnlyNonProdPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']
  BillingRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'PlatformBilling'
      ManagedPolicyArns: 
        - !Ref BillingPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']
  DevOpsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'PlatformDevOps'
      ManagedPolicyArns: 
        - !Ref DevOpsPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']
  DevOpsNonProdRole:
    Type: 'AWS::IAM::Role'
    Condition: IsNonProd
    Properties:
      RoleName: !Sub 'PlatformDevOpsNonProd'
      ManagedPolicyArns: 
        - !Ref DevOpsNonProdPolicy
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AdminAccount}:root
            Action: 'sts:AssumeRole'
            Condition:
              BoolIfExists: 
                aws:MultiFactorAuthPresent: !If [ShouldEnforceMFA, "true", !Ref 'AWS::NoValue']

  AdminsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: "Full Platform Admin Access"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - '*'
            Resource: '*'
      ManagedPolicyName: !Sub 'PlatformAdmins'
  PowerUsersPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: "Full Access to General Resources and Read Only Access to some Platform Resources"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            NotAction:
              - iam:*
              - organizations:*
              - account:*
              - kms:*
              - aws-portal:*
              - budgets:*
              - ce:*
              - cur:*
              - purchase-orders:*
              # TODO acm *, r53 *
            Resource: '*'
          - Effect: Allow
            Action:
              # TODO IAM Role and Role Create / Edit Policy
              - kms:List*
              - kms:Describe*
              - iam:List*
              - iam:Describe*
              - iam:*LinkedRole
              - organizations:DescribeOrganization
              - account:ListRegions
            Resource: '*'
      ManagedPolicyName: !Sub 'PlatformPowerUsers'
  PowerUsersNonProdPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsNonProd
    Properties: 
      Description: "PowerUser Access to General Non Prod Resources and Read Only Access to some Platform Resources"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            NotAction:
              - iam:*
              - organizations:*
              - account:*
              - kms:*
              - aws-portal:*
              - budgets:*
              - ce:*
              - cur:*
              - purchase-orders:*
            # TODO NON PROD ONLY
            Resource: '*'
          - Effect: Allow
            Action:
              # TODO IAM Role and Role Create / Edit Policy
              - kms:List*
              - kms:Describe*
              - iam:List*
              - iam:Describe*
              - iam:*LinkedRole
              - organizations:DescribeOrganization
              - account:ListRegions
            # TODO NON PROD ONLY
            Resource: '*'
      ManagedPolicyName: !Sub 'PlatformPowerUsersNonProd'
  ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: Read Only Access to General Resources and Read Only Access to some Platform Resources"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            NotAction:
              - iam:*
              - organizations:*
              - account:*
              - cloudformation:*
              - kms:*
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:ListRoles
            Resource: '*'
      ManagedPolicyName: !Sub 'PlatformReadOnly'
  ReadOnlyNonProdPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsNonProd
    Properties: 
      Description: Read Only Access to General Non Prod Resources and Read Only Access to some Platform Resources"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            NotAction:
              - iam:*
              - organizations:*
              - account:*
              - cloudformation:*
              - kms:*
            Resource: '*'
          - Effect: Allow
            Action:
              - iam:ListRoles
            Resource: '*'
      ManagedPolicyName: !Sub 'PlatformReadOnlyNonProd'
  BillingPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: "Full Access to Billing Console"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - aws-portal:*Billing
              - aws-portal:*Usage
              - aws-portal:*PaymentMethods
              - budgets:ViewBudget
              - budgets:ModifyBudget
              - ce:UpdatePreferences
              - ce:CreateReport
              - ce:UpdateReport
              - ce:DeleteReport
              - ce:CreateNotificationSubscription
              - ce:UpdateNotificationSubscription
              - ce:DeleteNotificationSubscription
              - cur:DescribeReportDefinitions
              - cur:PutReportDefinition
              - cur:ModifyReportDefinition
              - cur:DeleteReportDefinition
              - purchase-orders:*PurchaseOrders
            Resource: '*'
      ManagedPolicyName: !Sub 'PlatformBilling'
  DevOpsPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: "Full Access to DevOps Resources (Code*, Cloudformation). Usually combined with Full ReadOnly Policy"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codecommit:*
              - codepipeline:*
              - codebuild:*
              - codedeploy:*
              - cloudformation:*
              - logs:List*
              - logs:Get*
              - logs:Describe*
              - logs:StartQuery
              - logs:StopQuery
              - logs:FilterLogEvents
            Resource: '*'
      ManagedPolicyName: !Sub 'PlatformDevOps'
  DevOpsNonProdPolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsNonProd
    Properties: 
      Description: "Full Access to Non Prod DevOps Resources (Code*, Cloudformation). Usually combined with Full ReadOnly Policy"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - codecommit:*
              - codepipeline:*
              - codebuild:*
              - codedeploy:*
              - cloudformation:*
              - logs:List*
              - logs:Get*
              - logs:Describe*
              - logs:StartQuery
              - logs:StopQuery
              - logs:FilterLogEvents
            Resource: '*'
            # TODO Non Prod Condition
      ManagedPolicyName: !Sub 'PlatformDevOpsNonProd'

  AdminsAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "Full Platform Admin Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformAdmins'
      ManagedPolicyName: !Sub 'PlatformAssumeAdmins'
  PowerUsersAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "PowerUsers Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformPowerUsers'
      ManagedPolicyName: !Sub 'PlatformAssumePowerUsers'
  PowerUsersNonProdAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "PowerUsersNonProd Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformPowerUsersNonProd'
      ManagedPolicyName: !Sub 'PlatformAssumePowerUsersNonProd'
  ReadOnlyAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "ReadOnly Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformReadOnly'
      ManagedPolicyName: !Sub 'PlatformAssumeReadOnly'
  ReadOnlyNonProdAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "ReadOnlyNonProd Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformReadOnlyNonProd'
      ManagedPolicyName: !Sub 'PlatformAssumeReadOnlyNonProd'
  BillingAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "Billing Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformBilling'
      ManagedPolicyName: !Sub 'PlatformAssumeBilling'
  DevOpsAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "DevOps Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformDevOps'
      ManagedPolicyName: !Sub 'PlatformAssumeDevOps'
  DevOpsNonProdAssumePolicy:
    Type: AWS::IAM::ManagedPolicy
    Condition: IsAdmin
    Properties: 
      Description: "DevOpsNonProd Role Assume Policy for Group"
      Path: "/"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'sts:AssumeRole'
            Resource: 
              - !Sub 'arn:aws:iam::*:role/PlatformDevOpsNonProd'
      ManagedPolicyName: !Sub 'PlatformAssumeDevOpsNonProd'

  AdminsGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformAdminsGroup'
      ManagedPolicyArns: 
        - !Ref AdminsAssumePolicy
      Path: /
  PowerUsersGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformPowerUsersGroup'
      ManagedPolicyArns: 
        - !Ref PowerUsersAssumePolicy
      Path: /
  PowerUsersNonProdGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformPowerUsersNonProdGroup'
      ManagedPolicyArns: 
        - !Ref PowerUsersNonProdAssumePolicy
      Path: /
  ReadOnlyGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformReadOnlyGroup'
      ManagedPolicyArns: 
        - !Ref ReadOnlyAssumePolicy
      Path: /
  ReadOnlyNonProdGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformReadOnlyNonProdGroup'
      ManagedPolicyArns: 
        - !Ref ReadOnlyNonProdAssumePolicy
      Path: /
  BillingGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformBillingGroup'
      ManagedPolicyArns: 
        - !Ref BillingAssumePolicy
      Path: /
  DevOpsGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformDevOpsGroup'
      ManagedPolicyArns: 
        - !Ref DevOpsAssumePolicy
      Path: /
  DevOpsNonProdGroup:
    Type: 'AWS::IAM::Group'
    Condition: IsAdmin
    Properties: 
      GroupName: !Sub 'PlatformDevOpsNonProdGroup'
      ManagedPolicyArns: 
        - !Ref DevOpsNonProdAssumePolicy
      Path: /
