AWSTemplateFormatVersion: '2010-09-09'
Description: >
  SAM Template for building and packaging lambdas for rulesengine pipelines
Parameters:
Resources:
    PipelineRole:
      Type: AWS::IAM::Role
      Properties:
          RoleName: !Sub '${AppCode}-CodePipelineRole'
          AssumeRolePolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Action: 
                  - 'sts:AssumeRole'
                  Effect: Allow
                  Principal:
                    Service: 
                      - lambda.amazonaws.com
          Path: /
    PipelineCommitFetchFunction:
      Type: AWS::Serverless::Function 
      Properties:
        CodeUri: 'pipeline-lambdas/pipeline-commitfetch-lambda/'
        Role:
          Fn::GetAtt:
          - PipelineRole
          - Arn
        Handler: lambda_function.lambda_handler
        Runtime: python3.8
        MemorySize: 512
        Timeout: 900
        FunctionName: !Sub 'PipelineCommitFetchLambda'
    PipelineCommitEventFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: 'pipeline-lambdas/pipeline-commitevent-lambda/'
        Role:
          Fn::GetAtt:
          - PipelineRole
          - Arn
        Handler: lambda_function.lambda_handler
        Runtime: python3.8
        MemorySize: 512
        Timeout: 120
        FunctionName: !Sub 'PipelineCommitEventLambda'
    PipelineNextExecutionFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: 'pipeline-lambdas/pipeline-nextexecution-lambda/'
        Role:
          Fn::GetAtt:
          - PipelineRole
          - Arn
        Handler: lambda_function.lambda_handler
        Runtime: python3.8
        MemorySize: 512
        Timeout: 120
        FunctionName: !Sub 'PipelineNextExecutionLambda'
