AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'The following CloudFormation deploys demo serverless resources'
Parameters:
  Environment:
    Type: 'String'
    Default: 'dev'
  AppCode:
    Type: 'String'
    Default: 'demo-serverless'
  TZ:
    Type: 'String'
    Default: 'Australia/Melbourne'
  SubnetIds:
    Type: 'String'
    Default: 'subnet-d6f10a9e,subnet-513f4709,subnet-0e33fd68'
  APICustomDomain:
    Type: 'String'
    Default: 'www.something.com'
Globals:
  Function:
    Environment:
      Variables:
        TZ: !Ref 'TZ'
Resources:
  ReportsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AppCode}-${Environment}-reports'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3'
              SSEAlgorithm: 'aws:kms'
      LoggingConfiguration:
        DestinationBucketName: !Sub '${AWS::AccountId}-logging'
        LogFilePrefix: s3serveraccesslogs/reports
  DataLoadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AppCode}-${Environment}-data-load'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !Sub 'arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/s3'
              SSEAlgorithm: 'aws:kms'
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName: !Sub '${AWS::AccountId}-logging'
        LogFilePrefix: s3serveraccesslogs/data-load
  UsersDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AppCode}-${Environment}-users'
      AttributeDefinitions:
        - AttributeName: 'userid'
          AttributeType: 'S'
        - AttributeName: 'firstname'
          AttributeType: 'S'
        - AttributeName: 'surname'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'userid'
          KeyType: 'HASH'
      BillingMode: 'PAY_PER_REQUEST'
      GlobalSecondaryIndexes:
        -
          IndexName: 'firstname-index'
          KeySchema:
            -
              AttributeName: 'firstname'
              KeyType: 'HASH'
          Projection:
            NonKeyAttributes:
              - 'surname'
              - 'userid'
            ProjectionType: 'INCLUDE'
        -
          IndexName: 'surname-index'
          KeySchema:
            -
              AttributeName: 'surname'
              KeyType: 'HASH'
          Projection:
            NonKeyAttributes:
              - 'firstname'
              - 'userid'
            ProjectionType: 'INCLUDE'
  ReportsDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${AppCode}-${Environment}-reports'
      AttributeDefinitions:
        - AttributeName: 'reportid'
          AttributeType: 'S'
        - AttributeName: 'date'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'reportid'
          KeyType: 'HASH'
      BillingMode: 'PAY_PER_REQUEST'
      GlobalSecondaryIndexes:
        -
          IndexName: 'date-index'
          KeySchema:
            -
              AttributeName: 'date'
              KeyType: 'HASH'
          Projection:
            NonKeyAttributes:
              - 'reportid'
            ProjectionType: 'INCLUDE'
        
  S3ReadWritePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub '${AppCode}-${Environment}-S3-ReadWrite-Policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 's3:ListBucket'
              - 's3:GetBucket*'
              - 's3:GetObject*'
              - 's3:PutObject'
              - 's3:PutObjectTagging'
              - 's3:DeleteObject'
              - 's3:DeleteObjectTagging'
              - 's3:ListMultipartUploadParts'
              - 's3:AbortMultipartUpload'
            Resource:
              - !Sub 'arn:aws:s3:::${AppCode}-${Environment}-reports'
              - !Sub 'arn:aws:s3:::${AppCode}-${Environment}-reports/*'
              - !Sub 'arn:aws:s3:::${AppCode}-${Environment}-data-load'
              - !Sub 'arn:aws:s3:::${AppCode}-${Environment}-data-load/*'
  DynamoReadWritePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub '${AppCode}-${Environment}-DynamoDB-ReadWrite-Policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'dynamodb:BatchGet*'
              - 'dynamodb:DescribeStream'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:Get*'
              - 'dynamodb:Query'
              - 'dynamodb:Scan'
              - 'dynamodb:BatchWrite*'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:PutItem'
            Resource:
              - !Sub '${UsersDynamoDBTable.Arn}'
              - !Sub '${UsersDynamoDBTable.Arn}/index/*'
              - !Sub '${ReportsDynamoDBTable.Arn}'
              - !Sub '${ReportsDynamoDBTable.Arn}/index/*'
  StepFunctionPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub '${AppCode}-${Environment}-StepFunction-Policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'states:Send*'
              - 'states:StartExecution'
            Resource:
              - !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${AppCode}-${Environment}-ReportEngine'
  CloudwatchPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: !Sub '${AppCode}-${Environment}-Cloudwatch-Policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'logs:CreateLog*'
              - 'logs:GetLog*'
              - 'logs:PutLog*'
              - 'logs:DescribeLog*'
              - 'logs:DeleteMessage*'
              - 'logs:ListLogDeliveries'
              - 'logs:UpdateLogDelivery'
              - 'logs:DeleteLogDelivery'
              - 'logs:PutResourcePolicy'
              - 'logs:DescribeResourcePolicies'
            Resource:
              - '*'

  StatesExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub '${AppCode}-${Environment}-StateMachineRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - !Sub states.${AWS::Region}.amazonaws.com
            Action: 'sts:AssumeRole'
          - Effect: 'Allow'
            Principal:
              Service:
                - !Sub events.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: "/"
      ManagedPolicyArns:
        - !Ref 'CloudwatchPolicy'
        - !Ref 'StepFunctionPolicy'
      Policies:
        - PolicyName: StatesExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                  - 'ecs:RunTask'
                  - 'iam:PassRole'
                Resource: '*'
  ReportEngineStateMachineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'step/${AWS::Region}/${AWS::AccountId}/${AppCode}-${Environment}-ReportEngineStateMachine'
  ReportEngineStateMachine:
    Type: 'AWS::StepFunctions::StateMachine'
    Properties:
      StateMachineName: !Sub '${AppCode}-${Environment}-ReportEngine'
      DefinitionString:
        !Sub
          - |-
            {
              "Comment": "Report Engine process",
              "StartAt": "ReportEngine",
              "States": {
                  "ReportEngine": {
                      "Type": "Task",
                      "Resource": "arn:aws:states:::ecs:runTask.waitForTaskToken",
                      "Parameters": {
                          "LaunchType": "FARGATE",
                          "Cluster": "${ServerlessECSCluster}",
                          "PlatformVersion": "1.4.0",
                          "TaskDefinition": "${ReportEngineTaskDefinition}",
                          "NetworkConfiguration": {
                              "AwsvpcConfiguration": {
                                  "Subnets": [
                                      "${NetworkA}",
                                      "${NetworkB}"
                                  ],
                                  "AssignPublicIp": "DISABLED"
                              }
                          },
                          "Overrides": {
                              "ContainerOverrides": [
                                  {
                                      "Name": "ReportEngine",
                                      "Environment": [
                                          {
                                              "Name": "taskToken",
                                              "Value.$": "$$.Task.Token"
                                          },
                                          {
                                              "Name": "executionId",
                                              "Value.$": "$$.Execution.Id"
                                          }
                                      ]
                                  }
                              ]
                          }
                      },
                      "HeartbeatSeconds": 3600,
                      "Retry": [
                          {
                              "ErrorEquals": [
                                  "States.ALL"
                              ],
                              "IntervalSeconds": 10,
                              "MaxAttempts": 2,
                              "BackoffRate": 1.2
                          }
                      ],
                      "End": true
                  }
              }
            }         
          -
            ServerlessECSCluster: !GetAtt 'ServerlessECSCluster.Arn'
            ReportEngineTaskDefinition: !Ref 'ReportEngineECSTaskDefinition'
            NetworkA: !Select [0, !Split [',', !Sub "${SubnetIds}"]]
            NetworkB: !Select [1, !Split [',', !Sub "${SubnetIds}"]]
      RoleArn: !GetAtt 'StatesExecutionRole.Arn'
      LoggingConfiguration:
        Destinations:
        - CloudWatchLogsLogGroup:
            LogGroupArn: !GetAtt 'ReportEngineStateMachineLogGroup.Arn'
        IncludeExecutionData: true
        Level: ALL
        Level: ERROR    

  Boto3Layer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      Description: !Sub 'Layer for boto3 "'
      ContentUri: ../src/layers/boto3/
      CompatibleRuntimes:
        - 'python3.8'
      LayerName: !Sub '${AppCode}-${Environment}-Boto3'
  CustomLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      Description: !Sub 'Layer for custom "'
      ContentUri: ../src/layers/custom/
      CompatibleRuntimes:
        - 'python3.8'
      LayerName: !Sub '${AppCode}-${Environment}-Custom'

  ServerlessECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AppCode}-${Environment}-cluster"  
  ServerlessECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
  ReportEngineECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "ecs-tasks.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
      - "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"
      - !Ref 'S3ReadWritePolicy'
      - !Ref 'DynamoReadWritePolicy'
      - !Ref 'CloudwatchPolicy'
      - !Ref 'StepFunctionPolicy'
  ReportEngineECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties: 
      ContainerDefinitions: 
        - 
          Cpu: 1024
          Environment: 
            - 
              Name: DDB_USER_TABLE_NAME
              Value: !Sub '${AppCode}-${Environment}-users'
            - 
              Name: DDB_REPORT_TABLE_NAME
              Value: !Sub '${AppCode}-${Environment}-reports'
            - 
              Name: S3_BUCKET_REPORTS
              Value: !Ref ReportsBucket
            - 
              Name: TZ
              Value: !Ref 'TZ'
          Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${AppCode}-${Environment}-report-engine:latest'
          LogConfiguration: 
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub 'ecs/${AWS::Region}/${AWS::AccountId}/${AppCode}-${Environment}-ReportEngine'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: "ecs"
          Memory: 2048
          MemoryReservation: 2048
          Name: ReportEngine
      Cpu: 1024
      ExecutionRoleArn: !Ref ServerlessECSTaskExecutionRole
      Memory: 2048
      NetworkMode: "awsvpc"
      RequiresCompatibilities: 
        - "FARGATE"
      TaskRoleArn: !Ref ReportEngineECSTaskRole
  ReportEngineECSLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub 'ecs/${AWS::Region}/${AWS::AccountId}/${AppCode}-${Environment}-ReportEngine'
  ReportEngineECRRepository:
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName:  !Sub ${AppCode}-${Environment}-report-engine
      RepositoryPolicyText:
        !Sub
          - |-
            {
                "Version": "2008-10-17",
                "Statement": [
                    {
                    "Sid": "new statement",
                    "Effect": "Allow",
                    "Principal": "*",
                    "Action": "*"
                    }
                ]
            }
          -
            AccountNumber: !Ref "AWS::AccountId"

  DataLoadFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda_function.lambda_handler'
      FunctionName: !Sub '${AppCode}-${Environment}-data-load'
      Runtime: 'python3.8'
      CodeUri: '../src/lambdas/dataload/'
      MemorySize: 2048
      Timeout: 300
      Tracing: 'Active'
      Layers:
        - !Ref 'CustomLayer'
        - !Ref 'Boto3Layer'
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - !Ref 'DynamoReadWritePolicy'
        - !Ref 'S3ReadWritePolicy'
      Environment:
        Variables:
          ENVIRONMENT: !Sub '${Environment}'
      Events:
        S3Event:
          Type: S3 
          Properties:
            Bucket: !Ref DataLoadBucket
            Events: s3:ObjectCreated:*
  UserAPIFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'lambda_function.lambda_handler'
      FunctionName: !Sub '${AppCode}-${Environment}-UserAPIFunction'
      Runtime: 'python3.8'
      CodeUri: '../src/lambdas/user_api/'
      MemorySize: 256
      Timeout: 300
      Tracing: 'Active'
      Policies:
        - 'AWSLambdaBasicExecutionRole'
        - !Ref 'DynamoReadWritePolicy'
        - !Ref 'S3ReadWritePolicy'
      Layers:
        - !Ref 'Boto3Layer'
        - !Ref 'CustomLayer'
      Environment:
        Variables:
          DDB_USER_TABLE_NAME: !Sub '${AppCode}-${Environment}-users'
          DDB_REPORT_TABLE_NAME: !Sub '${AppCode}-${Environment}-reports'
      Events:
        UsersList:
          Type: Api 
          Properties:
            Path: /users
            Method: get
            RestApiId: !Ref UserAPI
        UserGet:
          Type: Api 
          Properties:
            Path: /users/{userid}
            Method: get
            RestApiId: !Ref UserAPI
        UserPost:
          Type: Api 
          Properties:
            Path: /users/{userid}
            Method: post
            RestApiId: !Ref UserAPI
        UserPut:
          Type: Api 
          Properties:
            Path: /users/{userid}
            Method: put
            RestApiId: !Ref UserAPI
        UserDelete:
          Type: Api 
          Properties:
            Path: /users/{userid}
            Method: delete
            RestApiId: !Ref UserAPI
        ReportsList:
          Type: Api 
          Properties:
            Path: /reports
            Method: get
            RestApiId: !Ref UserAPI
  UserAPICloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
  UserAPIAccount:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt 
        - UserAPICloudWatchRole
        - Arn
  UserAPILogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub 'API-Gateway-Execution-Logs_${AppCode}-${Environment}-UserAPI'
  UserAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub '${AppCode}-${Environment}-UserAPI'
      StageName: v1
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: PER_API
          Description: Usage plan for this API
          Throttle:
            BurstLimit: 200
            RateLimit: 100
      AccessLogSetting:
        DestinationArn: !GetAtt UserAPILogGroup.Arn
        Format: >-
          {"requestId":"$context.requestId", "ip": "$context.identity.sourceIp",
          "caller":"$context.identity.caller",
          "user":"$context.identity.user","requestTime":"$context.requestTime",
          "eventType":"$context.eventType","routeKey":"$context.routeKey",
          "status":"$context.status","connectionId":"$context.connectionId"}
      MethodSettings:
        - MetricsEnabled: true
          HttpMethod: "*"
          LoggingLevel: "INFO"
          ResourcePath: "/*"
       
  ReportSchedule:
    Type: AWS::Events::Rule
    Properties:
      Description: Run the Report Engine SFN at the specified intervals.
      ScheduleExpression: 'cron(0 1 * * ? *)'
      State: DISABLED
      Targets:
      - Id: ReportEngineStateMachineTarget
        Arn: !Ref ReportEngineStateMachine
        RoleArn: !GetAtt 
          - StatesExecutionRole
          - Arn