AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a simple test resource for demo pipelines
Parameters:
  AppCode:
      Description: Short Name for the Application being deployed in this template, to be used in resource and stack names
      Type: String
      Default: demo-pipeline
  Environment:
      Description: Short Name for the Environment being deployed in this template, to be used in resource and stack names
      Type: String
      Default: demo
Resources:
  TestLogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: !Sub '${AppCode}-${Environment}-LogGroup'
