version: 0.2

env:
  variables:
    BUILD_BUCKET: "238160719262-builds"
    CLOUDFORMATION_BUCKET: "238160719262-cloudformation"
    DEPLOYMENT_ROLE: ""
    APP_CODE: ""
    ENVIRONMENT: "env"
    PARAMS: ""
  exported-variables:
    - PARAMS 

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      # Install Git Client
      - apt-get update
      - apt-get install --assume-yes docker sudo
      - pip3 uninstall --yes awscli
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install --update
      - echo Configuring AWS CLI
      - aws --version
        
  build:
    commands:

      - echo Build any code here

  post_build:
    commands:
      - export PARAMS=Build-1234
      - echo Build completed on `date`
